### ISSUE TITLE
Create a menu

### ISSUE THREAD

**Issue by umumtaz1** [umumtaz1/python-exercise#1]
**User story**

As a user, I want to have the option to quit after starting the menu, so that I can perform other tasks after running this program.

*persona: User that is using the program.
*feature: Quit option for the menu.
*business value: User can exit the program and perform other tasks.  

**Task List**

- [x] Create a menu with quit option.
- [x] If user enters wrong option then menu will reappear
- [x] If user pushes q then the program will terminate.

**Acceptance Criteria**
1. Program exits after typing in the quit option.
2. If something else is entered, menu reappears.

**Acceptance Tests**
1. User runs query.py and types anything other than quit option
2. User types in the quit option.
